# Read the documentation: https://github.com/FriendsOfSymfony/FOSOAuthServerBundle/blob/master/Resources/doc/index.md#step-5-configure-fosoauthserverbundle
fos_oauth_server:
    db_driver: orm

    client_class: App\Shared\Infrastructure\Doctrine\ORM\Entity\Client
    access_token_class: App\Shared\Infrastructure\Doctrine\ORM\Entity\AccessToken
    refresh_token_class: App\Shared\Infrastructure\Doctrine\ORM\Entity\RefreshToken
    auth_code_class: App\Shared\Infrastructure\Doctrine\ORM\Entity\AuthCode
